import {  Roboto } from "next/font/google";
import "./globals.css";
import DesktopNav from "@/components/custom/desktopNav";
import MobileNav from "@/components/custom/mobileNav";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"], 
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  </head>
      <body
        className={`${roboto.variable} antialiased`}
      >
      <div className="h-screen bg-background">
      <DesktopNav />
      <main className="md:ml-64 pb-16 md:pb-0">
        <div className="page-container">{children}</div>
      </main>
      <MobileNav />
    </div>
      </body>
    </html>
  );
}
